#! /bin/sh

mkdir /proc
mount -t proc none /proc
mount -t devtmpfs none /dev
modprobe tun

brctl addbr br0
ip addr flush dev eth0
brctl addif br0 eth0
tunctl -t tap0 -u 0
tunctl -t tap1 -u 0
brctl addif br0 tap0
brctl addif br0 tap1

ifconfig eth0 up
ifconfig tap0 up
ifconfig tap1 up
ifconfig br0 up

cat > /etc/udhcpc.d/60nfsroot <<EOF
#! /bin/sh
env > /udhcpc.env
EOF
chmod 755 /etc/udhcpc.d/60nfsroot
udhcpc -i br0 -O rootpath

cmdline=$(tr ' ' '\n' < /proc/cmdline)

bootarg() {
	echo "$cmdline" | grep "$1" | cut -f2- -d'='
}

root=$(bootarg "root=")

mkdir /newroot

if [ -z "$root" ] || [ "$root" = "/dev/nfs" ]; then
	eval "$(grep rootpath= /udhcpc.env)"

	rootfstype=nfs
	rootflags=$(echo "${rootpath}" | cut -d, -f2-)
	root=$(echo "${rootpath}" | cut -d, -f1)

	# TODO: how about dhcpc's files?
else
	rootfstype=$(bootarg "rootfstype=")
	rootflags=$(bootarg "rootflags=")
fi

flags=""
[ -n "$rootfstype" ] && flags="$flags -t$rootfstype"
[ -n "$rootflags" ] && flags="$flags -o$rootflags"

mount $flags $root /newroot

exec switch_root /newroot /sbin/init
