#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    cat << EOF
Run QEMU as virtio device provider for seL4 VMs.

usage: $0 [-h|--help]
EOF
    exit 0
fi

# rootfs for guest
GUEST_IMG="${GUEST_IMG:-/var/lib/virt/images/user-vm.qcow2}"
# directory shared to guest
GUEST_SHARED="${GUEST_SHARED:-$HOME/.local/share/virt/shared}"
mkdir -p "$GUEST_SHARED"

GUEST_GUI_ARGS="${GUEST_GUI_ARGS:--vga none -display none}"

QEMU_APPEND_BOOTARGS=""
QEMU_EXTRA_ARGS="${GUEST_GUI_ARGS}"

# Decode args like 'uservm=1,0x48000000,0x10000000,0x60000000,0x10000000'
# TODO: use device tree
GUEST_MEMSZ=`while read -d' ' p; do
    echo $p | grep '^uservm=1,' | cut -f3 -d, | xargs -Isz printf "%d" sz
done < /proc/cmdline`

if test -n "${GUEST_MEMSZ}"; then
    # using seL4
    GUEST_MEMSZ=`expr ${GUEST_MEMSZ} / 1048576`
    ACCEL=sel4
fi
GUEST_MEMSZ=${GUEST_MEMSZ:-256}

if test "x${ACCEL}" = "xsel4"; then
    modprobe sel4_virt
else
    # using something else, let's default to KVM
    QEMU_APPEND_BOOTARGS="${QEMU_APPEND_BOOTARGS} console=hvc0 root=/dev/vda2"
    QEMU_EXTRA_ARGS="${QEMU_EXTRA_ARGS} -kernel /boot/Image -cpu host"
    ACCEL=kvm
fi

ulimit -c unlimited

exec /usr/bin/qemu-system-aarch64 \
    `# minicom already uses ^A, change monitor escape to ^T` \
    -echr 0x14 \
    `# do not touch these` \
    --accel ${ACCEL} \
    -M virt \
    -m ${GUEST_MEMSZ}m \
    `# virtio-blk device for guest rootfs` \
    -device virtio-blk-pci,drive=drive0,id=virtblk0 \
    -drive format=qcow2,file=${GUEST_IMG},if=none,id=drive0 \
    `# share directory to guest over 9P` \
    -virtfs local,path=${GUEST_SHARED},mount_tag=shared,security_model=mapped-xattr \
    `# debug messages, use monitor to read them` \
    -chardev ringbuf,id=debug,size=64K \
    `# enable multiplexer on stdio to have both guest and monitor` \
    -chardev stdio,id=mon,mux=on,signal=off \
    `# enable monitor` \
    -mon chardev=mon,mode=readline \
    `# virtio-console` \
    -device virtio-serial-pci \
    -device virtconsole,chardev=mon,id=console0,name=qemu.uservm \
    `# TUN/TAP networking` \
    -netdev tap,id=net0,ifname=tap0,script=no,downscript=no \
    -device virtio-net-pci,netdev=net0 \
    `# no serial, emulating pl011 @ 0x09000000 in seL4 code` \
    -serial none \
    `# extra options` \
    ${QEMU_EXTRA_ARGS} \
    ${QEMU_APPEND_BOOTARGS:+-append "${QEMU_APPEND_BOOTARGS}"} \
    `# that's it!`
